sudo: required

before_install:
  - mkdir bin build tmp
  - sudo apt install -y libegl1-mesa-dev
  - sudo apt install -y libgles2-mesa-dev
  - sudo apt install -y libsdl2-dev

addons:
  apt:
    update: true
  sonarcloud:
    organization: "minigamedusale"
    token: $SONAR_TOKEN
language: c++

compiler:
  - gcc
script:
	- make clean
	- build-wrapper-linux-x86-64 --out-dir bw-output make
	- make test
  - sonar-scanner