sudo: required

before_install:
  - mkdir bin build tmp
  - sudo apt install -y libegl1-mesa-dev
  - sudo apt install -y libgles2-mesa-dev
  - sudo apt install -y libsdl2-dev

addons:
  apt:
    update: true
  sonarcloud:
    organization: "chocotmorin"
    token: $SONAR_TOKEN
language: c++

compiler:
  - gcc
script:
  - make
  - sonar-scanner